---
title: "Temperature Trends"
output:
  html_document:
    df_print: paged
---
[Visit my main page](https://plummquat.github.io/IanPlummer/)

[More Interactive Maps](https://plummquat.github.io/IanPlummer/Figs.html)

*Disclaimer: All of the data displayed here comes from the Japanese Meteorological Agency and this page nor its authors are associated with this organization. For all official information regarding weather and climate in Japan, please visit the [JMA website](https://www.jma.go.jp/jma/indexe.html).*


```{r, include=FALSE, message =FALSE}
library("tidyverse")
library("leaflet")
```

```{r, include=FALSE, message=FALSE, warning=FALSE}
jpd<- read_csv("/Users/ip367316/Downloads/JMASpatial.csv")
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
jpd %>%
leaflet(width = 1000) %>%
addProviderTiles(providers$Esri.WorldImagery, group = "World Imagery") %>%
#addProviderTiles(providers$Stamen.TonerLite, group = "Toner Lite") %>%
addLayersControl(baseGroups = c("World Imagery","Toner Lite")) %>%
addMarkers(label = jpd$`Location`, 
           popup = jpd$Trends )
```

